workflows:
  ios-release-no-signature:
    name: iOS Release (No Signature)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter build ios --release --no-codesign
      - mkdir -p build/ios/ipa/Payload
      - cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
      - cd build/ios/ipa && zip -r Runner.ipa Payload
    artifacts:
      - build/ios/ipa/Runner.ipa
